### ISSUE TITLE
Cisco\cdb-8p - Duplicate key

### ISSUE THREAD

**Issue by dudeisbrendan03** [netbox-community/devicetype-library#345]
Duplicate key in a device
```
Creating template power-ports with {'name': 'PSU0', 'type': 'iec-60320-c14', 'maximum_draw': 236, 'device_type': 196}
Created new power-ports: PSU0
Traceback (most recent call last):
  File ".\netbox_import.py", line 327, in <module>
    process_yaml(yfile)
  File ".\netbox_import.py", line 318, in process_yaml
    device_type = load_yaml(yml_file)
  File ".\netbox_import.py", line 180, in load_yaml
    return yaml.load(stream)
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\main.py", line 343, in load
    return constructor.get_single_data()
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 257, in construct_mapping
    if self.check_mapping_key(node, key_node, mapping, key, value):
  File "C:\Users\Brendan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ruamel\yaml\constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "C:\Users\Brendan\Downloads\devicetype-library-master\__temp__\devicetype-library\device-types\Cisco\cdb-8p.yaml", line 1, column 1
found duplicate key "u_height" with value "0" (original value: "0")
  in "C:\Users\Brendan\Downloads\devicetype-library-master\__temp__\devicetype-library\device-types\Cisco\cdb-8p.yaml", line 8, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
```

**Comment by dudeisbrendan03** [comment]
#346

**Comment by dudeisbrendan03** [comment]
@ryanmerolle there's a significant amount of these with duplicate keys?

Later versions of ruamel yaml don't let you suppress the error anymore

**Comment by ryanmerolle** [comment]
Yep I am already working on a pre-commit and GitHub action to check for this. Should be complete in the next day or so.
